config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]

  resources :bands do
    resources :albums, only: [:new]
  end

  resources :albums, only: [:create, :show, :edit, :update, :destroy] do
    resources :tracks, only: [:new]
  end

  resources :tracks, only: [:create, :show, :edit, :update, :destroy]

  resources :notes, only: [:create, :destroy]
end

app/models/album.rb
class Album < ActiveRecord::Base
  validates :name, :band_id, :year, :kind, presence: true
  validates :kind, inclusion: { in: %w(live studio) }

  belongs_to :band
  has_many :tracks, dependent: :destroy
end

app/models/band.rb
class Band < ActiveRecord::Base
  validates :name, presence: true

  has_many :albums, dependent: :destroy
  has_many :tracks, dependent: :destroy,
    through: :albums
end

app/models/note.rb
class Note < ActiveRecord::Base
  validates :body, :user_id, :track_id, presence: true

  belongs_to :track
  belongs_to :user
end

app/models/track.rb
class Track < ActiveRecord::Base
  validates :name, :album_id, :ord, :kind, :lyrics, presence: true
  validates :kind, inclusion: { in: %w(standard bonus) }

  belongs_to :album
  has_one :band,
    through: :album
  has_many :notes
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :email, :password_digest, :session_token, presence: true
  validates :email, :session_token, uniqueness: true
  validates :password, length: { minimum: 8, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :notes

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user
    user.is_password?(password) ? user : nil
  end

  def self.generate_session_token
    SecureRandom.urlsafe_base64(32)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def reset_session_token!
    self.session_token = User.generate_session_token
    until self.save
      self.session_token = User.generate_session_token
    end
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    pw_digest = BCrypt::Password.new(self.password_digest)
    pw_digest.is_password?(password)
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action only: [:edit, :show, :update, :destroy] { ensure_exists "Album" }
  before_action :ensure_current_user

  def new
    @album = Album.new(band_id: params[:band_id])
    @band = Band.find_by(id: params[:band_id])
    render :new
  end

  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash.now[:errors] = @album.errors.full_messages
      render :new
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])
    render :edit
  end

  def show
    @album = Album.find_by(id: params[:id])
    @tracks = @album.tracks
    @band = @album.band
    render :show
  end

  def update
    @album = Album.find_by(id: params[:id])
    @album.update(album_params)
    redirect_to album_url(@album)
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @band = @album.band
    @album.destroy
    redirect_to album_url(@band)
  end

  def set_band

  end

  private

  def album_params
    params.require(:album).permit(:name, :band_id, :kind, :year)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
    redirect_to bands_url
  end

  def logout_user!
    current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to new_session_url
  end

  def logged_in?
    current_user ? true : false
  end

  def ensure_no_current_user
    redirect_to user_url(current_user) if logged_in?
  end

  def ensure_current_user
    redirect_to new_session_url unless current_user
  end

  def ensure_exists(class_name)
    unless class_name.constantize.exists?(id: params[:id])
      flash[:errors] = ["Could not find that #{class_name.downcase}"]
      redirect_to bands_url
    end
  end
end

app/controllers/bands_controller.rb
class BandsController < ApplicationController
  before_action only: [:update, :edit] { ensure_exists "Band" }
  before_action :ensure_current_user

  def index
    @bands = Band.all
    render :index
  end

  def new
    @band = Band.new
    render :new
  end

  def create
    @band = Band.new(band_params)

    if @band.save
      redirect_to band_url(@band)
    else
      flash.now[:errors] = @band.errors.full_messages
      render :new
    end
  end

  def edit
    @band = Band.find_by(id: params[:id])
    render :edit
  end

  def show
    @band = Band.find_by(id: params[:id])
    @albums = @band.albums
    render :show
  end

  def update
    @band = Band.find_by(id: params[:id])
    @band.update(band_params)
    redirect_to band_url(@band)
  end

  def destroy
    @band = Band.find_by(id: params[:id])
    @band.destroy
    redirect_to bands_url
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  def create
    @note = Note.new(note_params)
    @note.user_id = current_user.id
    @note.save
    redirect_to track_url(@note.track_id)
  end

  def destroy
    @note = Note.find_by(id: params[:id])
    @note.destroy
  end

  private

  def note_params
    params.require(:note).permit(:body, :track_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :ensure_no_current_user, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])

    if @user
      login_user!(@user)
    else
      flash.now[:errors] = ["That user doesn't exist."]
      @user = User.new
      render :new
    end
  end

  def destroy
    logout_user!
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action only: [:edit, :show, :update, :destroy] { ensure_exists "Track" }
  before_action :ensure_current_user

  def new
    @track = Track.new(album_id: params[:album_id])
    @album = Album.find_by(id: params[:album_id])
    render :new
  end

  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash.now[:errors] = @track.errors.full_messages
      render :new
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])
    render :edit
  end

  def show
    @track = Track.find_by(id: params[:id])
    @album = @track.album
    @notes = @track.notes
    render :show
  end

  def update
    @track = Track.find_by(id: params[:id])
    @track.update(track_params)
    redirect_to track_url(@track)
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @album = @track.album
    @track.destroy
    redirect_to album_url(@album)
  end

  private

  def track_params
    params.require(:track).permit(:name, :album_id, :ord, :kind, :lyrics)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_no_current_user, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login_user!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    render :show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bands_helper.rb
module BandsHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/albums/_album.html.erb
<li><%= link_to "#{album.name}", album_url(album) %></li>

app/views/albums/_form.html.erb
<% action = album.persisted? ? album_url(album) : albums_url %>
<% method = album.persisted? ? "PATCH" : "POST" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <p>
    <label>Name:
      <input type="text" name="album[name]" value="<%= @album.name %>">
    </label>
  </p>

  <p>
    <label>
      <select name="album[band_id]">
        <% Band.all.each do |band| %>
          <option value="<%= band.id %>" <%= @album.band_id == band.id ? "selected" : "" %>><%= band.name %></option>
        <% end %>
      </select>
    </label>
  </p>

  <p>
    <label>Live
      <input type="radio" name="album[kind]" value="live" <%= @album.kind == "live" ? "checked" : "" %>>
    </label>

    <label>Studio
      <input type="radio" name="album[kind]" value="studio" <%= @album.kind == "studio" ? "checked" : "" %>>
    </label>
  </p>

  <p>
    <label>Year:
      <input type="number" name="album[year]" value="<%= @album.year %>">
    </label>
  </p>

  <input type="submit" name="Submit">
</form>

app/views/albums/edit.html.erb
<h1>Edit <%= @album.name %></h1>

<%= render "form", album: @album %>

app/views/albums/new.html.erb
<h1>New Album for <%= @band.name %>!</h1>

<%= render "form", album: @album %>

app/views/albums/show.html.erb
<h1><%=  @album.name %></h1>

<section>
  <header><b>Tracks</b></header>

  <ul>
     <%= render @tracks %>
  </ul>
</section>

<nav>
  <header><b>Links</b></header>

  <ul>
    <li><%= link_to "New Track", new_album_track_url(@album) %></li>
    <li><%= link_to "Edit Album", edit_album_url(@album), method: :get %></li>
    <li><%= link_to "Delete Album", album_url(@album), method: :delete %></li>
    <li><%= link_to "Back to #{@band.name}", band_url(@band) %></li>
  </ul>
</nav>

app/views/bands/_band.html.erb
<li><%= link_to "#{band.name}", band_url(band) %></li>

app/views/bands/_form.html.erb
<% action = band.persisted? ? band_url(band) : bands_url %>
<% method = band.persisted? ? "PATCH" : "POST" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <label>Name:
    <input type="text" name="band[name]" value="<%= @band.name %>">
  </label>

  <input type="submit" name="Submit">
</form>

app/views/bands/edit.html.erb
<h1>Edit Band</h1>

<%= render "form", band: @band %>

app/views/bands/index.html.erb
<h1>Bands</h1>
  <ul>
    <%= render @bands %>
  </ul>
<%= link_to "New Band", new_band_url %>

app/views/bands/new.html.erb
<h1>New Band!</h1>

<%= render "form", band: @band %>

app/views/bands/show.html.erb
<h1><%=  @band.name %></h1>

<section>
  <header><b>Albums</b></header>

  <ul>
    <%= render @albums %>
  </ul>
</section>

<nav>
  <header><b>Links</b></header>

  <ul>
    <li><%= link_to "New Album", new_band_album_url(@band) %></li>
    <li><%= link_to "Edit Band", edit_band_url(@band), method: :get %></li>
    <li><%= link_to "Delete Band", band_url(@band), method: :delete %></li>
    <li><%= link_to "All Bands", bands_url %></li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <% if flash[:errors] %>
    <ul>
    <% flash[:errors].each do |error| %>
      <li><%= error %></li>
    <% end %>
    </ul>
  <% end %>

  <% if logged_in? %>
    <p>Logged in as: <%= current_user.email %></p>
    <%= button_to "Logout", session_url, method: :delete %>
    <br>
    <%= link_to "<- Back to All Bands", bands_url %>
  <% end %>
</header>

<%= yield %>

</body>
</html>

app/views/notes/_form.html.erb
<form action="notes_url" method="post">

  <p>
    <label>Content
      <textarea name="note[body]" rows="8" cols="40"></textarea>
    </label>
  </p>

  <input type="hidden" name="note[track_id]" value="track.id">

  <input type="submit" name="Submit">

</form>

app/views/notes/_notes.html.erb
<section>
  <p>
    <%= note.body %>
  </p>

  <p>
    Authored by: <%= User.find_by(id: note.user_id).email %>
  </p>

  <p>
    <%= button_to "Destroy note", note_url(note), method: :delete %>
  </p>

</section>

app/views/tracks/_form.html.erb
<% action = track.persisted? ? track_url(track) : tracks_url %>
<% method = track.persisted? ? "PATCH" : "POST" %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method %>">

  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <p>
    <label>Name:
      <input type="text" name="track[name]" value="<%= @track.name %>">
    </label>
  </p>

  <p>
    <label>
      <select name="track[album_id]">
        <% Album.all.each do |album| %>
          <option value="<%= album.id %>" <%= @track.album_id == album.id ? "selected" : "" %>><%= album.name %></option>
        <% end %>
      </select>
    </label>
  </p>

  <p>
    <label>Ord:
      <input type="number" name="track[ord]" value=<%= @track.ord %>>
    </label>
  </p>

  <p>
    <label>Standard
      <input type="radio" name="track[kind]" value="standard" <%= @track.kind == "standard" ? "checked" : "" %>>
    </label>

    <label>Bonus
      <input type="radio" name="track[kind]" value="bonus" <%= @track.kind == "bonus" ? "checked" : "" %>>
    </label>
  </p>

  <p>
    <label>Lyrics:
      <textarea name="track[lyrics]" rows="8" cols="40"><%= @track.lyrics %></textarea>
    </label>
  </p>

  <input type="submit" name="Submit">
</form>

app/views/tracks/_track.html.erb
<li><%= link_to "#{track.name}", track_url(track) %></li>

app/views/tracks/edit.html.erb
<h1>Edit <%= @track.name %></h1>

<%= render "form", track: @track %>

app/views/tracks/new.html.erb
<h1>New Track for <%= @album.name %>!</h1>

<%= render "form", track: @track %>

app/views/tracks/show.html.erb
<h1><%=  @track.name %></h1>

<section>
  <%= @track.lyrics %>
</section>

<section>
  <h2>New Note</h2>
  <%= render "note/form", track: @track %>
</section>

<section>
  <h2>Notes</h2>
  <%= render @notes %>
</section>

<br>
<nav>
  <header><b>Links</b></header>

  <ul>
    <li><%= link_to "Edit Track", edit_track_url(@track), method: :get %></li>
    <li><%= link_to "Delete Track", track_url(@track), method: :delete %></li>
    <li><%= link_to "Back to #{@album.name}", album_url(@album) %></li>
  </ul>
</nav>

app/views/users/new.html.erb
<h1>Sign up!</h1>

<form action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

  <p>
    <label>Email:
      <input type="text" name="user[email]" value="<%= @user.email %>">
    </label>
  </p>

  <p>
    <label>Password:
      <input type="text" name="user[password]">
    </label>
  </p>

  <input type="submit" name="Submit">
</form>
<br>
<br>
<%= button_to "Login", new_session_url, method: :get %>

app/views/users/show.html.erb
<%= current_user.email %>